### ISSUE TITLE
Suggestion / recipe for exporting decorated functions

### ISSUE THREAD

**Issue by dimaqq** [pybee/rubicon-objc#28]
For example:

```
def logged(f):
    @functools.wraps(f)
    def inner(*args, **kwargs):
        return f(*args, **kwargs)
    return inner


class CantRoller(UIViewController):
    @objc_method
    @logged
    def collectionView_cellForItemAtIndexPath_(self, view, path):
        ...
```

This fails at runtime with:

```
Traceback (most recent call last):
  File "ui/__main__.py", line 102, in inner
    return f(*args, **kwargs)
TypeError: collectionView_cellForItemAtIndexPath_() missing 2 required positional arguments: 'view' and 'path'
Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 234, in 'calling callback function'
  File ".../site-packages/rubicon/objc/objc.py", line 1003, in _objc_method
    result = f(py_self, *args)
  File ".../site-packages/ui/__main__.py", line 102, in inner
    return f(*args, **kwargs)
TypeError: collectionView_cellForItemAtIndexPath_() missing 2 required positional arguments: 'view' and 'path'
```

I'm guessing rubicon looked up `inner`'s function signature at `objc_method` decoration time and now at call time doesn't pass the arguments?

Actually I'm confused what's wrong...

**Comment by dgelessus** [comment]
Okay, I came up with a short(-ish) example which I think triggers the same issue:

```python
import ctypes.util
import functools

import rubicon.objc

Foundation_path = ctypes.util.find_library("Foundation")
assert Foundation_path is not None
Foundation = ctypes.CDLL(Foundation_path)

def logged(f):
    @functools.wraps(f)
    def inner(*args, **kwargs):
        return f(*args, **kwargs)
    return inner

_data = [
    rubicon.objc.at("one"),
    rubicon.objc.at("two"),
    rubicon.objc.at("three"),
]

class DGArray(rubicon.objc.ObjCClass("NSArray")):
    @rubicon.objc.objc_method
    @logged
    def count(self) -> rubicon.objc.NSUInteger:
        return 3
    
    @rubicon.objc.objc_method
    @logged
    def objectAtIndex_(self, index: rubicon.objc.NSUInteger):
        return _data[index]

if __name__ == "__main__":
    arr = DGArray.alloc().init()
    print(arr.count)
    print(arr.objectAtIndex_(0))
    print(arr.objectAtIndex_(1))
    print(arr.objectAtIndex_(2))
```

When I run that script, it produces:

```python
3
Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 234, in 'calling callback function'
  File "/Users/Shared/_Zeug/Python/projects/rubicon-objc/rubicon/objc/objc.py", line 1008, in _objc_method
    result = f(py_self, *args)
  File "/Users/Shared/_Zeug/Python/projects/rubicon-objc/testscript.py", line 13, in inner
    return f(*args, **kwargs)
TypeError: objectAtIndex_() missing 1 required positional argument: 'index'

Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)
```

So it seems that wrapped methods are always detected as taking no arguments, which is why the no-arg method `count` is working, but `objectAtIndex:` is not.

Most likely the fix to make `objc_method` and friends "look past" any wrappers, by looking at the `__wrapped__` attribute. (`functools.wraps` calls `update_wrapper`, which sets `__wrapped__` on the wrapped function.) I'll see if I can get this to work.
