### ISSUE TITLE
iOS error - ValueError: Library 'c' not found

### ISSUE THREAD

**Issue by davidferguson** [pybee/rubicon-objc#44]
(crossposting from https://github.com/pybee/briefcase/issues/48)

I'm trying to use briefcase to make an iOS app, but am finding that when I follow the second tutorial and try and run the app on a physical device, it crashes with the following error:

```2017-05-26 14:00:53.570 Tutorial 0[11917:5779110] PythonHome is: /var/containers/Bundle/Application/C6D15E50-4F2F-41B3-9CEE-CF09CF1D4637/Tutorial 0.app/Library/Python.framework/Resources
2017-05-26 14:00:53.583 Tutorial 0[11917:5779110] PYTHONPATH is: PYTHONPATH=/var/containers/Bundle/Application/C6D15E50-4F2F-41B3-9CEE-CF09CF1D4637/Tutorial 0.app/Library/Application Support/org.pibakery.tutorial_0/app:/var/containers/Bundle/Application/C6D15E50-4F2F-41B3-9CEE-CF09CF1D4637/Tutorial 0.app/Library/Application Support/org.pibakery.tutorial_0/app_packages
2017-05-26 14:00:53.584 Tutorial 0[11917:5779110] Initializing Python runtime
2017-05-26 14:00:54.830 Tutorial 0[11917:5779110] Running /var/containers/Bundle/Application/C6D15E50-4F2F-41B3-9CEE-CF09CF1D4637/Tutorial 0.app/Library/Application Support/org.pibakery.tutorial_0/app/tutorial_0/__main__.py
Traceback (most recent call last):
  File "/var/containers/Bundle/Application/C6D15E50-4F2F-41B3-9CEE-CF09CF1D4637/Tutorial 0.app/Library/Application Support/org.pibakery.tutorial_0/app/tutorial_0/__main__.py", line 1, in <module>
    from tutorial_0.app import main
  File "/var/containers/Bundle/Application/C6D15E50-4F2F-41B3-9CEE-CF09CF1D4637/Tutorial 0.app/Library/Application Support/org.pibakery.tutorial_0/app/tutorial_0/app.py", line 1, in <module>
    import toga
  File "/var/containers/Bundle/Application/C6D15E50-4F2F-41B3-9CEE-CF09CF1D4637/Tutorial 0.app/Library/Application Support/org.pibakery.tutorial_0/app_packages/toga/__init__.py", line 114, in <module>
    set_platform()
  File "/var/containers/Bundle/Application/C6D15E50-4F2F-41B3-9CEE-CF09CF1D4637/Tutorial 0.app/Library/Application Support/org.pibakery.tutorial_0/app_packages/toga/__init__.py", line 86, in set_platform
    local_vars['platform'] = importlib.import_module(module_name)
  File "/var/containers/Bundle/Application/C6D15E50-4F2F-41B3-9CEE-CF09CF1D4637/Tutorial 0.app/Library/Python.framework/Resources/lib/python35.zip/importlib/__init__.py", line 126, in import_module
  File "/var/containers/Bundle/Application/C6D15E50-4F2F-41B3-9CEE-CF09CF1D4637/Tutorial 0.app/Library/Application Support/org.pibakery.tutorial_0/app_packages/toga_iOS/__init__.py", line 2, in <module>
    from .app import *
  File "/var/containers/Bundle/Application/C6D15E50-4F2F-41B3-9CEE-CF09CF1D4637/Tutorial 0.app/Library/Application Support/org.pibakery.tutorial_0/app_packages/toga_iOS/app.py", line 1, in <module>
    from rubicon.objc import objc_method
  File "/var/containers/Bundle/Application/C6D15E50-4F2F-41B3-9CEE-CF09CF1D4637/Tutorial 0.app/Library/Application Support/org.pibakery.tutorial_0/app_packages/rubicon/objc/__init__.py", line 3, in <module>
    from .objc import (
  File "/var/containers/Bundle/Application/C6D15E50-4F2F-41B3-9CEE-CF09CF1D4637/Tutorial 0.app/Library/Application Support/org.pibakery.tutorial_0/app_packages/rubicon/objc/objc.py", line 27, in <module>
    c = cdll.LoadLibrary(_find_or_error('c'))
  File "/var/containers/Bundle/Application/C6D15E50-4F2F-41B3-9CEE-CF09CF1D4637/Tutorial 0.app/Library/Application Support/org.pibakery.tutorial_0/app_packages/rubicon/objc/objc.py", line 23, in _find_or_error
    raise ValueError("Library {!r} not found".format(name))
ValueError: Library 'c' not found
2017-05-26 14:00:58.937 Tutorial 0[11917:5779110] Application quit abnormally!
2017-05-26 14:00:59.029 Tutorial 0[11917:5779110] Leaving
```

If I run the same app on the Simulator instaed, everything works fine:

```2017-05-26 14:30:10.383 Tutorial 0[2607:70813] PythonHome is: /Users/David/Library/Developer/CoreSimulator/Devices/53742BCD-50FC-4DA8-B85D-6938B1888F3B/data/Containers/Bundle/Application/A85A882F-8322-4C1D-B62F-D919722D4999/Tutorial 0.app/Library/Python.framework/Resources
2017-05-26 14:30:10.614 Tutorial 0[2607:70813] PYTHONPATH is: PYTHONPATH=/Users/David/Library/Developer/CoreSimulator/Devices/53742BCD-50FC-4DA8-B85D-6938B1888F3B/data/Containers/Bundle/Application/A85A882F-8322-4C1D-B62F-D919722D4999/Tutorial 0.app/Library/Application Support/org.pibakery.tutorial_0/app:/Users/David/Library/Developer/CoreSimulator/Devices/53742BCD-50FC-4DA8-B85D-6938B1888F3B/data/Containers/Bundle/Application/A85A882F-8322-4C1D-B62F-D919722D4999/Tutorial 0.app/Library/Application Support/org.pibakery.tutorial_0/app_packages
2017-05-26 14:30:10.615 Tutorial 0[2607:70813] Initializing Python runtime
2017-05-26 14:30:11.032 Tutorial 0[2607:70813] Running /Users/David/Library/Developer/CoreSimulator/Devices/53742BCD-50FC-4DA8-B85D-6938B1888F3B/data/Containers/Bundle/Application/A85A882F-8322-4C1D-B62F-D919722D4999/Tutorial 0.app/Library/Application Support/org.pibakery.tutorial_0/app/tutorial_0/__main__.py
App finished launching.
```

The simulator is running iOS 9.3, the iPad is running iOS 9.3., and I'm using Xcode 7.3.1 on Mac 10.11.6.

**Comment by davidferguson** [comment]
Upon further testing, I've found (as was expected) that when run on the physical device, the output of the python:

```from ctypes import util
print(util.find_library('c'))
print(util.find_library('objc'))
print(util.find_library('Foundation'))
```
is:

```
None
None
None
```

**Comment by dgelessus** [comment]
(Copying what I posted on Gitter.)

It's an issue with the iOS sandbox. iOS pretends that all system libraries don't exist on the filesystem, but you can still load them with `ctypes`:

```python
>>> import os
>>> import ctypes
>>> os.stat("/usr/lib/libc.dylib")
Traceback (most recent call last):
	File <string>, line 1, in <module>:
		# Source code unavailable

exceptions.OSError: [Errno 2] No such file or directory: '/usr/lib/libc.dylib'
>>> ctypes.CDLL("/usr/lib/libc.dylib")
Out[3] = <CDLL '/usr/lib/libc.dylib', handle ffeeddcc00000000 at 108cf46a0>
```

This confuses `ctypes.util.find_library`, which thinks the libraries don't exist.

**Comment by tleeuwenburg** [comment]
It looks like this is the same issue as #44. I don't actually know where briefcase is storing everything or what the filesystem is, so I don't know how to tell for sure if I'm running with this merge request included. But I'm still experiencing the issue.

**Comment by tleeuwenburg** [comment]
Okay, I managed to find the copy of Rubicon I had inside XCode, copy/pasted this, and it works for me too.

**Comment by freakboy3742** [comment]
If you use a trunk version of rubicon, that should also address the problem. If you're able to confirm that this works, it would be most helpful.
