### ISSUE TITLE
Error during the importation of rubicon.objc

### ISSUE THREAD

**Issue by lilouch** [pybee/rubicon-objc#9]
Hi,

I'm trying to use rubicon-obj but I'm not able to compile it.
In a python shell, when I write this command line : 
**from rubicon.objc import ObjCClass, objc_method**
I get this error : 
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/rubicon/objc/__init__.py", line 5, in <module>
    from .objc import (
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/rubicon/objc/objc.py", line 1354
    def dealloc(self, cmd) -> None:
                           ^
SyntaxError: invalid syntax
```

I did pip install **pip install rubicon-objc**

Coud you please help me ? Thank 
Regards

**Comment by freakboy3742** [comment]
Hi - the problem is that you're using Python 2.7; Rubicon-objc requires some syntax extensions that are Python 3 specific.
